#!/bin/bash

set -o errexit
set -o nounset

ADDRESS=$1
PORT=$2
CGMINER_COMMAND=$3
ITEM=$4

# https://github.com/ckolivas/cgminer/blob/master/API-README

COMMAND="{\"command\":\"$CGMINER_COMMAND\"}"
RET=`echo -n $COMMAND | nc $ADDRESS $PORT | sed 's/}{/},{/' | sed 's/\x0//g'`
#-#echo '$RET = ' $RET
# "S" -- Success
echo $RET | jq '.STATUS[0].STATUS' | grep -q 'S'
#-#echo '${CGMINER_COMMAND^^}[0][\"${ITEM}\"] = ' ${CGMINER_COMMAND^^}[0][\"${ITEM}\"]
echo $RET | jq ".${CGMINER_COMMAND^^}[0][\"${ITEM}\"]"
