#!/bin/bash

set -o errexit
set -o nounset

ADDRESS=$1
PORT=$2
CGMINER_COMMAND=$3
ITEM=$4
#LEVEL=$5

# https://github.com/ckolivas/cgminer/blob/master/API-README

COMMAND="{\"command\":\"$CGMINER_COMMAND\"}"
RET=`curl -s -u yongyi:yongyi $ADDRESS/api/overview`
#-#echo '$RET = ' $RET

# "S" -- Success
#echo $RET | jq '.STATUS[0].STATUS' | grep -q 'S'

#-#echo $RET | jq ".${CGMINER_COMMAND^^}[$LEVEL][\"${ITEM}\"]"
echo $RET | jq ".\"${CGMINER_COMMAND}\".\"${ITEM}\""
